// pipeline {
// 	agent any
// 	stages {
// 		stage('Build') {
// 			steps{
// 				sh 'echo "Build completed."'
// 			}
// 		}
// 	}
// }


pipeline {
	agent any
	tools {
		maven "MAVEN3.9"
		jdk "JDK17"
	}
	stages {
		stage ('Fetch Code') {
			steps {
				git branch: 'atom' , url : 'https://github.com/hkhcoder/vprofile-project.git'
			}
		}
		stage ('Unit Test') {
			steps {
				sh 'mvn test'
			}
		}
		stage ('Build') {
			steps {
				sh 'mvn install -DskipTests'
			}
			post {
				echo 'Archiving Artifact'
				archiveArtifacts artifacts: '**/*.war'
			}
		}
	}
}